sudo: false
language: ruby
rvm:
- 2.0.0
before_install: gem install bundler -v 1.11.2
script:
- pwd
- cd dummy
- bundle install && bundle exec rake test:unit
- cd ..
deploy:
  provider: rubygems
  edge:
    source: vishrutshah/dpl
    branch: gemspec_with_path
  api_key:
    secure: 13245768
  gemspec: dummy/azure-core.gemspec
  gem: azure-core
  on:
    tags: true
    repo: vishrutshah/azure-ruby-asm-core
